export const BRUSH_COLORS = ['black', 'red', 'blue'];

export const COLORS_MODAL = ['#a3ddcb', '#e8e9a1', '#e6b566', '#e56f7e'];

export const BRUSH_SIZES = [2, 5, 10];

export const MODE_TYPES = {
  ERASER: 'ERASER',
  ROUND: 'round',
  LINE: 'line',
};

export const SHAPE_TYPE = {
  ROUND: 'round',
  LINE: 'line',
};

export const ACTIONS = {
  SET_CANVAS: 'SET_CANVAS',
  SET_CANVAS_CONTEXT: 'SET_CANVAS_CONTEXT',
  SET_BRUSH_COLOR: 'SET_BRUSH_COLOR',
  SET_LINE_WIDTH: 'SET_LINE_WIDTH',
  SET_MODE_TYPE: 'SET_MODE_TYPE',
  SET_CANVAS_HISTORY: 'SET_CANVAS_HISTORY',
  SET_CANVAS_HISTORY_OF_RECONVERY: 'SET_CANVAS_HISTORY_OF_RECONVERY',
  SET_TEMPLATE_CANVAS: 'SET_TEMPLATE_CANVAS',
  SET__TEMPLATE_CANVAS_CONTEXT: 'SET__TEMPLATE_CANVAS_CONTEXT',
};
