export const BRUSH_COLORS = ['black', 'red', 'blue'];

export const BRUSH_SIZES = [2, 5, 20];

export const MODE_TYPES = {
  ERASER: 'ERASER',
  ROUND: 'round',
  LINE: 'line',
};

export const SHAPE_TYPE = {
  ROUND: 'round',
  LINE: 'line',
};

export const ACTIONS = {
  SET_CANVAS: 'SET_CANVAS',
  SET_CANVAS_CONTEXT: 'SET_CANVAS_CONTEXT',
  SET_BRUSH_COLOR: 'SET_BRUSH_COLOR',
  SET_LINE_WIDTH: 'SET_LINE_WIDTH',
  SET_MODE_TYPE: 'SET_MODE_TYPE',
  SET_CANVAS_HISTORY: 'SET_CANVAS_HISTORY',
  SET_CANVAS_HISTORY_OF_RECONVERY: 'SET_CANVAS_HISTORY_OF_RECONVERY',
};
